### ISSUE TITLE
pod install后编译找不到GPBAny 类定义

### ISSUE THREAD

**Issue by wonderffee** [goodow/GDDataDrivenView#4]
Xcode有报错cannot find interface declaration for 'GPBAny'，但是搜了一下  interface GPBAny 实际上是有的，感觉像是头文件引用的问题，观察到  Build Setting->Preprocessor Macros 中GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1 也设置为1了，很奇怪

**Comment by larrytin** [comment]
注释掉.m里一个 gpbany的扩展，好像叫 wellknowntypes

wonderffee <notifications@github.com>于2018年1月16日 周二下午5:47写道：

**Comment by wonderffee** [comment]
这就有点坑了

**Comment by larrytin** [comment]
这个问题可能是Protobuf的podspec问题

wonderffee <notifications@github.com>于2018年1月16日 周二下午6:20写道：

**Comment by larrytin** [comment]
可能是 Protobuf 的问题, 暂时这样解决:
找到文件: Pods/Protobuf/objectivec/GPBWellKnownTypes.h
注释掉该文件中对 GPBAny 的扩展 GBPWellKnownTypes 部分

```objc
//@interface GPBAny (GBPWellKnownTypes)
//...
//@end
```
